extends: capitalization
message: |
  Use sentence-style capitalization for '%s'.

  If your heading uses sentence capitalization but this error is reported, you need to add an exception to https://github.com/grafana/writers-toolkit/blob/main/vale/Grafana/Headings.yml.
link: "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
level: warning
scope: heading
match: $sentence
threshold: 0.6
exceptions:
  - Adaptive Metrics
  - Application Observability
  - CLA
  - Cloud Logs
  - Cloud Metrics
  - Cloud Traces
  - CPU
  - Grafana
  - Grafana Cloud
  - Grafana Cloud Traces
  - Grafana Enterprise Logs
  - Grafana Enterprise Metrics
  - Grafana Enterprise Traces
  - Grafana Labs
  - Helm
  - HTTP
  - Hugo
  - Kinesis Data Firehose
  - Kubernetes Monitoring
  - LogQL
  - Loki
  - macOS
  - Memcached
  - Mimir
  - Prometheus
  - PromQL
  - Redis
  - SRE
  - Tempo
  - TraceQL
  - What's new
  - Writers' Toolkit
  - YouTube
