extends: capitalization
message: "Use sentence-style capitalization for '%s'."
link: "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
level: warning
scope: heading
match: $sentence
exceptions:
  - Adaptive Metrics
  - Application Observability
  - Cloud Metrics
  - Cloud Logs
  - Cloud Traces
  - CPU
  - Grafana
  - Grafana Cloud
  - Grafana Enterprise Metrics
  - Grafana Enterprise Logs
  - Grafana Enterprise Traces
  - Grafana Labs
  - Helm
  - HTTP
  - Hugo
  - Kinesis Data Firehose
  - Kubernetes Monitoring
  - LogQL
  - Loki
  - macOS
  - Memcached
  - Mimir
  - Prometheus
  - PromQL
  - Redis
  - Tempo
  - TraceQL
  - What's new
  - YouTube
  - Grafana Cloud Traces
