extends: substitution
message: "Use '%s' instead of '%s'."
link: "https://developers.google.com/style/word-list"
level: warning
ignorecase: false
action:
  name: replace
swap:
  "(?:API Console|dev|developer) [Kk]ey": API key
  "(?:OAuth ?2|Oauth)": OAuth 2.0
  "(?:WiFi|wifi)": Wi-Fi
  "(?:[aA]daptive metrics|adaptive Metrics)": Adaptive Metrics
  "(?:[gG]itHub]|Github)": GitHub
  "(?:alert[Mm]anager|[Aa]lert [Mm]anager|AlertManager)": Alertmanager
  "(?:cell ?phone|smart ?phone)": phone|mobile phone
  "(?:dev|developer|APIs) console": API console
  "(?:e-mail|Email|E-mail)": email
  "(?:file ?path|path ?name)": path
  "(?:hamburger menu|kebab menu)": menu icon
  "(?:hold the pointer over|point to)": hover over
  "(?:kill|terminate|abort)": stop|exit|cancel|end
  "(?:ok|Okay)": OK|okay
  "[^/]grafana[^/]": Grafana
  "[cC]entos": CentOS
  "[cC]ontact support": contact Support
  "back[ -]end": backend
  "front[ -]end": frontend
  "left[- ]hand[- ]side": left-side
  "right[- ]hand[- ]side": right-side
  "tap (?:&|and) hold": touch and hold
  "un(?:check|select)": clear
  '3\-D': 3D
  'Google (?:I\-O|IO)': Google I/O
  '[\.]+apk': APK
  API Key: API key
  Ajax: AJAX
  Android device: Android-powered device
  Container Engine: Kubernetes Engine
  De-duplicate: Deduplicate
  Developers Console: API console
  GME: GEM
  Google API explorer: Google APIs Explorer
  Googling: search with Google
  HTTPs: HTTPS
  Once: After
  SHA1: SHA-1|HAS-SHA1
  World Wide Web: web
  above: preceding
  admin: administrator
  android: Android
  approx\.: approximately
  authN: authentication
  authZ: authorization
  autoupdate: automatically update
  blacklist: blocklist
  chapter: documents|pages|sections
  check box: checkbox
  check: select
  config file: configuration file
  content type: media type
  curated roles: predefined roles
  data-?source: data source
  datacenter: data center
  de-duplicate: deduplicate
  dialog box appears: dialog box opens
  dialog: dialog box
  drop down: drop-down
  dropdown: drop-down
  ephemeral IP address: ephemeral external IP address
  fewer data: less data
  file name: filename
  firewalls: firewall rules
  grayed-out: unavailable
  in order to: to
  ingest: import|load
  k8s: Kubernetes
  log(?:ql|QL): LogQL
  loki: Loki
  long press: touch and hold
  markdown: Markdown
  memcached: Memcached
  meta data: metadata
  mix[ -]in: mixin
  modal: dialog box
  mysql: MySQL
  network IP address: internal IP address
  omnibox: address bar
  open-source: open source
  overview screen: recents screen
  phlare: Phlare
  postgres: Postgres
  postgresql: PostgreSQL
  prom(?:ql|QL): PromQL
  prometheus: Prometheus
  promtail: Promtail
  redis: Redis
  regex: regular expression
  repo: repository
  sign into: sign in to
  sign-?on: single sign-on
  sqlite: SQLite
  static IP address: static external IP address
  stylesheet: style sheet
  synch: sync
  tablename: table name
  tablet: device
  tempo: Tempo
  the Grafana Agent: Grafana Agent
  timeseries: time series|time-series
  touch: tap
  trace(?:ql|QL): TraceQL
  url: URL
  vs\.: versus
  whitelist: allowlist

  Data Firehose: Kinesis Data Firehose
  Firehose: Kinesis Data Firehose
  Kinesis Firehose: Kinesis Data Firehose

  pod: Pod

  ad[- ]?hoc: free-form|user-written
